# Generated by Django 5.0.7 on 2024-07-22 13:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
                ('family', models.CharField(max_length=350)),
                ('phone', models.CharField(max_length=350)),
                ('ncode', models.CharField(max_length=350)),
                ('score', models.CharField(max_length=350)),
                ('descripion', models.CharField(max_length=350)),
                ('totals', models.CharField(max_length=350)),
                ('profiles', models.ImageField(upload_to='')),
                ('date_add_totals', models.DateField(default=django.utils.timezone.now)),
                ('date_add_score', models.DateField(default=django.utils.timezone.now)),
                ('date_create', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True)),
                ('all_totals', models.CharField(max_length=350)),
                ('Type_person', models.CharField(choices=[('getter', 'تسویه'), ('setter', 'بدهکار')], default='getter', max_length=10)),
            ],
        ),
    ]
