# Generated by Django 5.0.7 on 2024-07-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='all_score',
            field=models.CharField(default=1, max_length=350),
            preserve_default=False,
        ),
    ]
